spring.application.name=tamboo
spring.datasource.url=jdbc:mysql://localhost:3306/tamboo
spring.datasource.username=user
spring.datasource.password=user123.
server.port=3000

jwt.secret=NkJiMzE3YWE1ZjY3ZDJjYmI1MjkzYmU0MzQyNDA1NzVkZjRlZGVmZDI0ZmI2ZjU2ZDQ3NTE2YjM2NzdiNjhlNw==
jwt.expirationMs=86400000

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG

#logging delle query
spring.jpa.show-sql=true